[versions]
agp = "8.2.0"
constraintlayoutCompose = "1.0.1"
converterGson = "2.9.0"
coreTesting = "2.1.0"
hiltAndroid = "2.46"
hiltNavigationCompose = "1.0.0"
kotlin = "1.8.20"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
kotlinxCoroutinesTest = "1.5.2"
kotlinxSerializationJson = "1.6.3"
composeBom = "2023.04.01"
loggingInterceptor = "4.10.0"
mockito = "3.11.2"
navigationCompose = "2.8.0-alpha08"
material3 = "1.2.0-alpha10"
retrofit = "2.9.0"
room = "2.5.1"
theme = "28a1702347"
torangrepository = "17a6bb5115"
addReviewVersion = '268f368236'
alarmVersion = '34ba26f49c'
baseFeedVersion = '6307ce6df9'
cardInfoVersion = "0ae8d4fd77"
feedVersion = 'd1477c5c91'
profileVersion = '68528c88b0'
findingVersion = '47ad95d530'
themeVersion = '28a1702347'
themesVersion = 'bdb00d9256'
myReviewVersion = '7788b8d9f7'
torangDetailVersion = '1f7f01f3fb'
loginVersion = 'ac5034132b'
splashVersion = 'ea97b19733'
torangRepositoryVersion = '17a6bb5115'
settingsVersion = '06efa47b11'
mapVersion = 'f7ff07fe0a'
torangBottomSheetVersion = 'c84399fb7f'
instaGramGalleryVersion = 'b506724857'
filterVersion = 'e6976ce972'
mainVersion = '04e8b58fa5'
reportVersion = 'bb52e7be2e'
mediaContentResolverVersion = '54ff69ee3a'
commentVersion = '13a0dff4c3'
commonImageLoaderVersion = 'd0446c327d'
imagePagerVersion = '35b42a2392'
torangImagePagerVersion = '1c6db113f1'
likesScreenVersion = 'adb7eb7479'
featureDeliveryVersion = "2.1.0"
serialization = "1.7.10"

# @formatter:off
[libraries]

# Navigation
nav-fragment-ktx                = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationCompose" }
nav-ui-ktx                      = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationCompose" }
nav-dynamic-features-fragment   = { group = "androidx.navigation", name = "navigation-dynamic-features-fragment", version.ref = "navigationCompose" }
nav-testing                     = { group = "androidx.navigation", name = "navigation-testing", version.ref = "navigationCompose" }
nav-compose                     = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
kotlinx-serialization-json      = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# Room
room-runtime                    = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler                   = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-paging                     = { group = "androidx.room", name = "room-paging", version.ref = "room" }

# Hilt
hilt                            = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltAndroid" }
hilt-compiler                   = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltAndroid" }
hilt-nav-compose                = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

# Test
junit                           = { group = "junit", name = "junit", version.ref = "junit" }
x-junit-ext                     = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
x-espresso-core                 = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
x-ui-test-junit4                = { group = "androidx.compose.ui", name = "ui-test-junit4" }
x-ui-test-manifest              = { group = "androidx.compose.ui", name = "ui-test-manifest" }
kotlinx-coroutines-test         = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
mockito-core                    = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-inline                  = { group = "org.mockito", name = "mockito-inline", version.ref = "mockito" }
core-testing                    = { group = "androidx.arch.core", name = "core-testing", version.ref = "coreTesting" }
hilt-testing                    = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hiltAndroid" }

# Compose
x-compose-bom                   = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
x-ui                            = { group = "androidx.compose.ui", name = "ui" }
x-ui-graphics                   = { group = "androidx.compose.ui", name = "ui-graphics" }
x-ui-tooling-preview            = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
x-ui-tooling                    = { group = "androidx.compose.ui", name = "ui-tooling" }
material3                       = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
material3-windows-size          = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "material3" }
lifecycle-runtime-compose       = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose" }
constraintlayout-compose        = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayoutCompose" }

# Retrofit
retrofit                        = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson                  = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converterGson" }
logging-interceptor             = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }

# Torang
theme                           = { group = "com.github.sarang628", name = "Theme", version.ref = "theme" }
basefeed                        = { group = "com.github.sarang628", name = "BaseFeed", version.ref = "baseFeedVersion" }
feed                            = { group = "com.github.sarang628", name = "Feed", version.ref = "feedVersion" }
alarm                           = { group = "com.github.sarang628", name = "Alarm", version.ref = "alarmVersion" }
profile                         = { group = "com.github.sarang628", name = "Profile", version.ref = "profileVersion" }
finding                         = { group = "com.github.sarang628", name = "Finding", version.ref = "findingVersion" }
myReview                        = { group = "com.github.sarang628", name = "MyReview", version.ref = "myReviewVersion" }
torangDetail                    = { group = "com.github.sarang628", name = "TorangDetail", version.ref = "torangDetailVersion" }
addReview                       = { group = "com.github.sarang628", name = "AddReview", version.ref = "addReviewVersion" }
login                           = { group = "com.github.sarang628", name = "Login", version.ref = "loginVersion" }
splash                          = { group = "com.github.sarang628", name = "Splash", version.ref = "splashVersion" }
torangRepository                = { group = "com.github.sarang628", name = "TorangRepository", version.ref = "torangrepository" }
settings                        = { group = "com.github.sarang628", name = "Settings", version.ref = "settingsVersion" }
cardInfo                        = { group = "com.github.sarang628", name = "CardInfo", version.ref = "cardInfoVersion" }
map                             = { group = "com.github.sarang628", name = "Map", version.ref = "mapVersion" }
torangBottomSheet               = { group = "com.github.sarang628", name = "TorangBottomSheet", version.ref = "torangBottomSheetVersion" }
instagramGallery                = { group = "com.github.sarang628", name = "InstagramGallery", version.ref = "instaGramGalleryVersion" }
filter                          = { group = "com.github.sarang628", name = "Filter", version.ref = "filterVersion" }
main                            = { group = "com.github.sarang628", name = "Main", version.ref = "mainVersion" }
report                          = { group = "com.github.sarang628", name = "Report", version.ref = "reportVersion" }
mediaContentResolver            = { group = "com.github.sarang628", name = "MediaContentResolver", version.ref = "mediaContentResolverVersion" }
comment                         = { group = "com.github.sarang628", name = "Comment", version.ref = "commentVersion" }
commonImageLoader               = { group = "com.github.sarang628", name = "CommonImageLoader", version.ref = "commonImageLoaderVersion" }
imagePager                      = { group = "com.github.sarang628", name = "ImagePager", version.ref = "imagePagerVersion" }
torangImagePager                = { group = "com.github.sarang628", name = "TorangImagePager", version.ref = "torangImagePagerVersion" }
likes                           = { group = "com.github.sarang628", name = "Likes", version.ref = "likesScreenVersion" }
themes                          = { group = "com.github.bingley1", name = "Themes", version.ref = "themesVersion" }
feature-delivery                = { group = "com.google.android.play", name = "feature-delivery"}
# @formatter:on

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }

